export const light = {
  name: "light-theme",
  colors: {
    mainColor: "#eaeaea",
    secondaryColor: "#fff",
    borderColor: "#c1c1c1",
    mainText: "black",
    secondaryText: "#4b5156",
    headerText: "black",
    paragraphText: "black",
    navBarColor: "#708090",
    gradient1: "#fec02f",
    gradient2: "#fec02f",
    navigationColor: "black",
    sidebarColor: "#edf2f7",
    rightWindowColor: "white",
    screenColor: "#c1c1c1",
  },
};

export const green = {
  name: "green-theme",
  colors: {
    mainColor: "black",
    secondaryColor: "#9cf965",
    borderColor: "#161914",
    mainText: "#9cf965",
    secondaryText: "#256f15",
    headerText: "#256f15",
    paragraphText: "#256f15",
    themeDotBorder: "#fff",
    previewBg: "rgb(81, 90, 72, 0.8)",
    previewShadow: "#2a2f25",
    inputFieldColor: "#acdf87",
    buttonColor: "#2a2f25",
    navBarColor: "#9cf965",
    skillList: "#fff",
    gradient1: "black",
    gradient2: "black",
    navigationColor: "#256f15",
    sidebarColor: "#cbf8b1",
    rightWindowColor: "white",
    screenColor: "black",
  },
};

export const purple = {
  name: "purple-theme",
  colors: {
    mainColor: "#46344E",
    secondaryColor: "#382a3f",
    borderColor: "#1d1520",
    mainText: "#fff",
    secondaryText: "#eeeeee",
    headerText: "#46344E",
    paragraphText: "#382a3f",
    themeDotBorder: "#fff",
    previewBg: "rgb(29, 21, 32, 0.8)",
    previewShadow: "#653780",
    inputFieldColor: "#e6e6fa",
    buttonColor: "#2a2f25",
    navBarColor: "#653780",
    skillList: "#fff",
    gradient1: "#c67ff2",
    gradient2: "#ac6dcc",
    navigationColor: "#382a3f",
    sidebarColor: "#d7a3f7",
    rightWindowColor: "white",
    screenColor: "#d7a3f7",
  },
};

export const blue = {
  name: "blue-theme",
  colors: {
    mainColor: "#0A192F",
    secondaryColor: "#8892B0",
    borderColor: "#307A77",
    mainText: "#fff",
    secondaryText: "#eeeeee",
    headerText: "#0A192F",
    paragraphText: "#0A192F",
    themeDotBorder: "#FFF",
    previewBg: "rgb(25, 39, 52, 0.8)",
    buttonColor: "#37546f",
    inputFieldColor: "#708090",
    previewShadow: "#111921",
    navBarColor: "#CCD6F7",
    gradient1: "#307A77",
    gradient2: "#307A77",
    navigationColor: "#0A192F",
    skillList: "#fff",
    sidebarColor: "#8892B0",
    rightWindowColor: "white",
    screenColor: "black",
  },
};
